
# https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/
variables:
  VM_IMAGE: macOS-12
  DEFAULT_NODE_VERSION: "16.x"
  XCODE_VERSION: "13.4"

pool:
  vmImage: "$(VM_IMAGE)"

parameters:
- name: analyzeJobs
  type: object
  default:
  - name: Analyze_Lib
    scheme: WebDriverAgentLib
  - name: Analyze_Runner
    scheme: WebDriverAgentRunner
  - name: Analyze_Tests
    scheme: IntegrationTests
  - name: Analyze_Test_App
    scheme: WebDriverAgent


stages:
- stage: Unit_Tests_And_Linters
  jobs:
  - job: Node_Unit_Tests
    steps:
    - template: .azure-templates/node_setup_steps.yml
    - script: |
        npm install -g appium@next
        npm install
        appium driver install --source=local .
    - script: npm run test
  - ${{ each job in parameters.analyzeJobs }}:
    - template: .azure-templates/base_job.yml
      parameters:
        name: ${{ job.name }}
        action: analyze
        scheme: ${{ job.scheme }}
        xcodeVersion: $(XCODE_VERSION)
        vmImage: $(VM_IMAGE)
