parameters:
    name: ''
    action: ''
    scheme: ''
    xcodeVersion: ''
    vmImage: ''


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: sudo xcode-select --switch "/Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer"
    - script: |
        cd WebDriverAgentMac
        xcodebuild -project "WebDriverAgentMac.xcodeproj" -scheme ${{ parameters.scheme }} ${{ parameters.action }}
