parameters:
    name: ''
    action: ''
    scheme: ''
    xcodeVersion: ''
    vmImage: ''


jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - script: sudo xcode-select --switch "/Applications/Xcode_${{ parameters.xcodeVersion }}.app/Contents/Developer"
    # retry once on bootstrap failure
    - script: |
        cd WebDriverAgentMac
        ./Scripts/bootstrap.sh -dn || (sleep $[ ( $RANDOM % 60 ) + 1 ]s && ./Scripts/bootstrap.sh -dn)
        xcodebuild -project "WebDriverAgentMac.xcodeproj" -scheme ${{ parameters.scheme }} ${{ parameters.action }}
